package kmwe.afw.infogame.model.enums;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum Genre {
    ACTION("ACTION"),
    PLATFORMER("PLATFORMER"),
    SHOOTER("SHOOTER"),
    FIGHTING("FIGHTING"),
    BEAT_EM_UP("BEAT-EM UP"),
    STELS_ACTION("STELS-ACTION"),
    SURVIVAL("SURVIVAL"),
    ACTION_ADVENTURE("ACTION-ADVENTURE"),
    RYTHM_GAME("RYTHM-GAME"),
    SURVIVAL_HORROR("SURVIVAL-HORROR"),
    METROIDWAVE("METROIDWAVE"),
    QUEST("QUEST"),
    TEXT_QUEST("TEXT QUEST"),
    GRAPHIC_QUEST("GRAPHIC QUEST"),
    VISUAL_NOVEL("VISUAL NOVEL"),
    INTERACTIVE_CINEMA("INTERACTIVE CINEMA"),
    THREE_D("3D"),
    TWO_D("2D"),
    ROLE_GAMES("ROLE GAMES"),
    ACTION_RPG("ACTION-RPG"),
    MMORPG("MMORPG"),
    ROGUELIKE("ROGUELIKE"),
    TACTICAL_RPG("TACTICAL RPG"),
    OPEN_WORLD_RPG("OPEN WORLD RPG"),
    FIRST_PERSON_PARTY_RPG("FIRST-PERSON PARTY RPG"),
    JRPG("JRPG"),
    GAME_GAGA("GAME GAGA"),
    SOULSLIKE("SOULSLIKE"),
    SIMULATORS("SIMULATORS"),
    CONSTRUCTION_AND_MANAGEMENT_SIMULATORS("CONSTRUCTION AND MANAGEMENT SIMULATORS"),
    SIMULATION_OF_LIFE("SIMULATION OF LIFE"),
    TECHNOLOGY_SIMULATORS("TECHNOLOGY SIMULATORS"),
    POLITICAL_SIMULATION("POLITICAL SIMULATION"),
    GODS_SIMULATOR("GOD'S SIMULATOR"),
    STRATEGIES("STRATEGIES"),
    FOURX_STRATEGIES("4X STRATEGIES"),
    RTS("RTS"),
    REAL_TIME_TACTICS("REAL-TIME TACTICS"),
    MOBA("MOBA"),
    TOWER_DEFENSE("TOWER DEFENSE"),
    TURN_BASED_STRATEGIES("TURN-BASED STRATEGIES"),
    STEP_BY_STEP_TACTICS("STEP BY STEP TACTICS"),
    WARGAMS("WARGAMS"),
    GLOBAL_STRATEGIES("GLOBAL STRATEGIES");

    private final String value;

    public String getValue() {
        return value;
    }
}
