server:
  port: 8082

spring:
  application:
    name: info-game

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/infogame
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: off
